import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import {
  BlankExperienceContentType,
  initContentTypeRegistry,
  config,
} from '@optimizely/cms-sdk';
import { initReactComponentRegistry, initForms } from '@optimizely/cms-sdk/react/server';

import './globals.css';
import Teaser, { TeaserContentType } from '@/components/base/Teaser';
import Editorial, { EditorialContentType } from '@/components/base/Editorial';
import Contact, { ContactContentType } from '@/components/base/Contact';
import Start, { StartContentType } from '@/components/Start';
import Product, { ProductContentType } from '@/components/Product';
import Standard, { StandardContentType } from '@/components/Standard';
import Notice, { NoticeContentType } from '@/components/base/Notice';
import News, { NewsContentType } from '@/components/News';
import Article, { ArticleContentType } from '@/components/base/Article';
import BlankSection from '@/components/base/BlankSection';
import { SEOContentType } from '@/components/base/SEO';
import Button, { ButtonContentType } from '@/components/base/Button';
import { TeaserCardContract } from '@/components/contracts/TeaserCard';
import StandardTeaser from '@/components/base/StandardTeaser';
import NewsEventsList, {
  NewsEventsListContentType,
} from '@/components/base/NewsEventsList';
import FormContainer from '@/components/forms/FormContainer';
import FormChoice from '@/components/forms/FormChoice';
import FormInput from '@/components/forms/FormInput';
import FormNumber from '@/components/forms/FormNumber';
import FormRange from '@/components/forms/FormRange';
import FormReset from '@/components/forms/FormReset';
import FormSelection from '@/components/forms/FormSelection';
import FormSubmit from '@/components/forms/FormSubmit';
import FormTextarea from '@/components/forms/FormTextarea';
import FormUrl from '@/components/forms/FormUrl';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Configure Optimizely Graph client
config({
  apiKey: process.env.OPTIMIZELY_GRAPH_SINGLE_KEY!,
  graphUrl: process.env.OPTIMIZELY_GRAPH_GATEWAY,
  fragment: {
    richTextFormat: 'json',
  },
  query: {
    host: process.env.APPLICATION_HOST,
  },
});

initContentTypeRegistry([
  ArticleContentType,
  BlankExperienceContentType,
  ContactContentType,
  EditorialContentType,
  NewsContentType,
  NoticeContentType,
  ProductContentType,
  StartContentType,
  TeaserContentType,
  StandardContentType,
  SEOContentType,
  ButtonContentType,
  TeaserCardContract,
  NewsEventsListContentType,
]);

initReactComponentRegistry({
  resolver: {
    Article,
    Contact,
    Editorial,
    News,
    Notice,
    Product,
    Standard: {
      default: Standard,
      tags: {
        teaser: StandardTeaser,
      },
    },
    Start,
    Teaser,
    BlankSection,
    Button,
    NewsEventsList,
  },
});

initForms({
  container: FormContainer,
  choice: FormChoice,
  number: FormNumber,
  range: FormRange,
  reset: FormReset,
  selection: FormSelection,
  submit: FormSubmit,
  textbox: FormInput,
  textarea: FormTextarea,
  url: FormUrl,
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
